#生产环境配置

server:
  # 服务端口
  port: 5000

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/xmchxcoder?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    url: jdbc:mysql://localhost:3306/graduate_manage1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&useSSL=false

# 开启权限拦截
auth:
  enabled: true

# 开启请求日志记录
request-log:
  enabled: true
